// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pIPBZsu0ep-t6iw063FEc8ADGRlZtAM',
    appId: '1:564688080407:web:0f95c790b3824ea2b89652',
    messagingSenderId: '564688080407',
    projectId: 'shoppingapp-e1541',
    authDomain: 'shoppingapp-e1541.firebaseapp.com',
    databaseURL: 'https://shoppingapp-e1541-default-rtdb.firebaseio.com',
    storageBucket: 'shoppingapp-e1541.firebasestorage.app',
    measurementId: 'G-JGSZYPHZMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDij4_Q4Hr_tXy8h3-th3ZL7R8dXwliFfA',
    appId: '1:564688080407:android:4502c62cee81775fb89652',
    messagingSenderId: '564688080407',
    projectId: 'shoppingapp-e1541',
    databaseURL: 'https://shoppingapp-e1541-default-rtdb.firebaseio.com',
    storageBucket: 'shoppingapp-e1541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06lio-8oAabSAIzSladvxAqV5PqQjjkk',
    appId: '1:564688080407:ios:6cbf37210d4a07dfb89652',
    messagingSenderId: '564688080407',
    projectId: 'shoppingapp-e1541',
    databaseURL: 'https://shoppingapp-e1541-default-rtdb.firebaseio.com',
    storageBucket: 'shoppingapp-e1541.firebasestorage.app',
    iosBundleId: 'com.example.multishoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06lio-8oAabSAIzSladvxAqV5PqQjjkk',
    appId: '1:564688080407:ios:6cbf37210d4a07dfb89652',
    messagingSenderId: '564688080407',
    projectId: 'shoppingapp-e1541',
    databaseURL: 'https://shoppingapp-e1541-default-rtdb.firebaseio.com',
    storageBucket: 'shoppingapp-e1541.firebasestorage.app',
    iosBundleId: 'com.example.multishoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3pIPBZsu0ep-t6iw063FEc8ADGRlZtAM',
    appId: '1:564688080407:web:644b3b3c03f8008eb89652',
    messagingSenderId: '564688080407',
    projectId: 'shoppingapp-e1541',
    authDomain: 'shoppingapp-e1541.firebaseapp.com',
    databaseURL: 'https://shoppingapp-e1541-default-rtdb.firebaseio.com',
    storageBucket: 'shoppingapp-e1541.firebasestorage.app',
    measurementId: 'G-42CFMND9SB',
  );
}
